import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { missions } from "@/data/chaon";
import { seedPosts, type Post } from "@/data/community";
import { supabase } from "@/lib/supabase";

export type Meetup = { id:string; title:string; date:string; time:string; place:string; maxPeople:number; joinedPeople:number; creator:string; avatar:string };
export type MusicRecommendation = { id:string; title:string; artist:string; date:string; recommender:string };
type State = { nickname:string; avatar:string; profileTags:string[]; points:number; badges:string[]; doneMissions:string[]; joinedPrograms:string[]; joinedEvents:string[]; visits:number; posts:Post[]; meetups:Meetup[]; musicVotes:Record<string,string>; musicRecommendations:MusicRecommendation[] };
const KEY="chaon.state.v3";
const initial:State={nickname:"",avatar:"🐤",profileTags:["친구랑 노는 걸 좋아해"],points:240,badges:["첫 방문","게임왕","친구왕"],doneMissions:[],joinedPrograms:[],joinedEvents:[],visits:4,posts:seedPosts,meetups:[],musicVotes:{},musicRecommendations:[]};
type Ctx=State&{ready:boolean;backendConnected:boolean;setProfile:(nickname:string,avatar:string)=>void;setProfileTags:(tags:string[])=>void;completeMission:(id:string)=>{point:number;badge?:string}|null;toggleProgram:(id:string)=>boolean;toggleEvent:(id:string)=>boolean;addPost:(text:string,place:string,image?:string)=>void;toggleLike:(id:string)=>void;addMeetup:(input:Omit<Meetup,"id"|"creator"|"avatar"|"joinedPeople">)=>void;toggleMeetup:(id:string)=>boolean;voteMusic:(date:string,songId:string)=>boolean;addMusicRecommendation:(title:string,artist:string,date:string)=>void};
const ChaonContext=createContext<Ctx|null>(null);

export function ChaonProvider({children}:{children:ReactNode}){
 const [state,setState]=useState<State>(initial); const [ready,setReady]=useState(false); const [userId,setUserId]=useState<string|null>(null);
 useEffect(()=>{ try{const raw=localStorage.getItem(KEY);if(raw)setState({...initial,...(JSON.parse(raw) as Partial<State>)});}catch{} setReady(true); },[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{}},[state,ready]);
 useEffect(()=>{
  if(!supabase)return;
  let mounted=true;
  const start=async()=>{let {data}=await supabase.auth.getSession(); if(!data.session){const r=await supabase.auth.signInAnonymously(); data=r.data;} if(!mounted||!data.session)return; const uid=data.session.user.id; setUserId(uid);
   const profile=await supabase.from("profiles").select("nickname,avatar,profile_tags,points,visits").eq("id",uid).maybeSingle();
   if(profile.data) setState(s=>({...s,nickname:profile.data.nickname??s.nickname,avatar:profile.data.avatar??s.avatar,profileTags:profile.data.profile_tags??s.profileTags,points:profile.data.points??s.points,visits:profile.data.visits??s.visits}));
   else await supabase.from("profiles").insert({id:uid,nickname:state.nickname||"익명의 차오름러",avatar:state.avatar,profile_tags:state.profileTags,points:state.points,visits:state.visits});
   const [posts,meetups,recs]=await Promise.all([supabase.from("posts").select("id,nickname,avatar,place,text,image,likes,comments,created_at").order("created_at",{ascending:false}).limit(100),supabase.from("meetups").select("id,title,date,time,place,max_people,joined_people,creator,avatar").order("created_at",{ascending:false}).limit(100),supabase.from("music_recommendations").select("id,title,artist,vote_date,recommender").order("created_at",{ascending:false}).limit(30)]);
   if(posts.data?.length) setState(s=>({...s,posts:posts.data.map((p:any)=>({id:p.id,nickname:p.nickname,avatar:p.avatar,place:p.place,text:p.text,image:p.image||undefined,likes:p.likes,comments:p.comments}))}));
   if(meetups.data) setState(s=>({...s,meetups:meetups.data.map((m:any)=>({id:m.id,title:m.title,date:m.date,time:m.time,place:m.place,maxPeople:m.max_people,joinedPeople:m.joined_people,creator:m.creator,avatar:m.avatar}))}));
   if(recs.data) setState(s=>({...s,musicRecommendations:recs.data.map((r:any)=>({id:r.id,title:r.title,artist:r.artist,date:r.vote_date,recommender:r.recommender}))}));
  }; void start();
  const channel=supabase.channel("chaon-live").on("postgres_changes",{event:"*",schema:"public",table:"posts"},()=>{void supabase.from("posts").select("id,nickname,avatar,place,text,image,likes,comments,created_at").order("created_at",{ascending:false}).limit(100).then(({data})=>{if(data?.length)setState(s=>({...s,posts:data.map((p:any)=>({id:p.id,nickname:p.nickname,avatar:p.avatar,place:p.place,text:p.text,image:p.image||undefined,likes:p.likes,comments:p.comments}))}));});}).on("postgres_changes",{event:"*",schema:"public",table:"meetups"},()=>{void supabase.from("meetups").select("id,title,date,time,place,max_people,joined_people,creator,avatar").order("created_at",{ascending:false}).limit(100).then(({data})=>{if(data)setState(s=>({...s,meetups:data.map((m:any)=>({id:m.id,title:m.title,date:m.date,time:m.time,place:m.place,maxPeople:m.max_people,joinedPeople:m.joined_people,creator:m.creator,avatar:m.avatar}))}));});}).subscribe();
  return()=>{mounted=false;void supabase.removeChannel(channel);};
 },[]);
 const setProfile=useCallback((nickname:string,avatar:string)=>{setState(s=>({...s,nickname,avatar}));if(supabase&&userId)void supabase.from("profiles").upsert({id:userId,nickname:nickname||"익명의 차오름러",avatar,profile_tags:state.profileTags,points:state.points,visits:state.visits,updated_at:new Date().toISOString()});},[userId,state.profileTags,state.points,state.visits]);
 const setProfileTags=useCallback((tags:string[])=>{const next=tags.slice(0,5);setState(s=>({...s,profileTags:next}));if(supabase&&userId)void supabase.from("profiles").upsert({id:userId,nickname:state.nickname||"익명의 차오름러",avatar:state.avatar,profile_tags:next,points:state.points,visits:state.visits,updated_at:new Date().toISOString()});},[userId,state.nickname,state.avatar,state.points,state.visits]);
 const completeMission=useCallback((id:string)=>{const mission=missions.find(m=>m.id===id);if(!mission)return null;let applied=false;setState(s=>{if(s.doneMissions.includes(id))return s;applied=true;return {...s,doneMissions:[...s.doneMissions,id],points:s.points+mission.point,badges:mission.badge&&!s.badges.includes(mission.badge)?[...s.badges,mission.badge]:s.badges};});return applied?{point:mission.point,badge:mission.badge}:null;},[]);
 const toggleProgram=useCallback((id:string)=>{let joined=false;setState(s=>{joined=!s.joinedPrograms.includes(id);return{...s,joinedPrograms:joined?[...s.joinedPrograms,id]:s.joinedPrograms.filter(p=>p!==id)}});return joined;},[]);
 const toggleEvent=useCallback((id:string)=>{let joined=false;setState(s=>{joined=!s.joinedEvents.includes(id);return{...s,joinedEvents:joined?[...s.joinedEvents,id]:s.joinedEvents.filter(e=>e!==id)}});return joined;},[]);
 const addPost=useCallback((text:string,place:string,image?:string)=>{setState(s=>{const post={id:`u${Date.now()}`,nickname:s.nickname||"익명의 차오름러",avatar:s.avatar,place,time:"방금",text,likes:0,comments:0,...(image?{image}:{})};if(supabase&&userId)void supabase.from("posts").insert({author_id:userId,nickname:post.nickname,avatar:post.avatar,place,text,image:image||null});return{...s,points:s.points+5,posts:[post,...s.posts]};});},[userId]);
 const toggleLike=useCallback((id:string)=>{setState(s=>({...s,posts:s.posts.map(p=>p.id===id?{...p,liked:!p.liked,likes:p.likes+(p.liked?-1:1)}:p)}));if(supabase)void supabase.from("posts").select("likes").eq("id",id).maybeSingle().then(({data})=>{if(data)void supabase.from("posts").update({likes:Math.max(0,data.likes+(1))}).eq("id",id);});},[]);
 const addMeetup=useCallback((input:Omit<Meetup,"id"|"creator"|"avatar"|"joinedPeople">)=>{setState(s=>{const creator=s.nickname||"익명의 차오름러";const meetup={...input,id:`meetup-${Date.now()}`,creator,avatar:s.avatar,joinedPeople:1};if(supabase&&userId)void supabase.from("meetups").insert({creator_id:userId,title:input.title,date:input.date,time:input.time,place:input.place,max_people:input.maxPeople,joined_people:1,creator,avatar:s.avatar});return{...s,meetups:[meetup,...s.meetups]};});},[userId]);
 const toggleMeetup=useCallback((id:string)=>{let joined=false;setState(s=>({...s,meetups:s.meetups.map(m=>{if(m.id!==id||m.joinedPeople>=m.maxPeople)return m;joined=true;return{...m,joinedPeople:m.joinedPeople+1}})}));return joined;},[]);
 const voteMusic=useCallback((date:string,songId:string)=>{let voted=false;setState(s=>{if(s.musicVotes[date])return s;voted=true;if(supabase&&userId)void supabase.from("music_votes").insert({user_id:userId,vote_date:date,song_id:songId});return{...s,musicVotes:{...s.musicVotes,[date]:songId},points:s.points+1};});return voted;},[userId]);
 const addMusicRecommendation=useCallback((title:string,artist:string,date:string)=>{setState(s=>{const recommender=s.nickname||"익명의 차오름러";if(supabase&&userId)void supabase.from("music_recommendations").insert({user_id:userId,title,artist,vote_date:date,recommender});return{...s,musicRecommendations:[{id:`song-${Date.now()}`,title,artist,date,recommender},...s.musicRecommendations].slice(0,30)}});},[userId]);
 const value=useMemo<Ctx>(()=>({...state,ready,backendConnected:Boolean(supabase&&userId),setProfile,setProfileTags,completeMission,toggleProgram,toggleEvent,addPost,toggleLike,addMeetup,toggleMeetup,voteMusic,addMusicRecommendation}),[state,ready,userId,setProfile,setProfileTags,completeMission,toggleProgram,toggleEvent,addPost,toggleLike,addMeetup,toggleMeetup,voteMusic,addMusicRecommendation]);
 return <ChaonContext.Provider value={value}>{children}</ChaonContext.Provider>;
}
export function useChaon(){const ctx=useContext(ChaonContext);if(!ctx)throw new Error("useChaon must be used inside ChaonProvider");return ctx;}
