/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It is checked in so deployed builds can resolve every file-based route.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgramsNearbyRouteImport } from './routes/programs/nearby'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces/$spaceId'
import { Route as MeetupRouteImport } from './routes/meetup'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const CommunityRoute = CommunityRouteImport.update({ id: '/community', path: '/community', getParentRoute: () => rootRouteImport } as any)
const EventsRoute = EventsRouteImport.update({ id: '/events', path: '/events', getParentRoute: () => rootRouteImport } as any)
const MissionsRoute = MissionsRouteImport.update({ id: '/missions', path: '/missions', getParentRoute: () => rootRouteImport } as any)
const ProfileRoute = ProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => rootRouteImport } as any)
const ProgramsRoute = ProgramsRouteImport.update({ id: '/programs', path: '/programs', getParentRoute: () => rootRouteImport } as any)
const ProgramsNearbyRoute = ProgramsNearbyRouteImport.update({ id: '/programs/nearby', path: '/nearby', getParentRoute: () => ProgramsRouteImport } as any)
const SpacesRoute = SpacesRouteImport.update({ id: '/spaces', path: '/spaces', getParentRoute: () => rootRouteImport } as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({ id: '/spaces/$spaceId', path: '/$spaceId', getParentRoute: () => SpacesRouteImport } as any)
const MeetupRoute = MeetupRouteImport.update({ id: '/meetup', path: '/meetup', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/programs/nearby': typeof ProgramsNearbyRoute
  '/spaces': typeof SpacesRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/meetup': typeof MeetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/programs/nearby': typeof ProgramsNearbyRoute
  '/spaces': typeof SpacesRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/meetup': typeof MeetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/programs/nearby': typeof ProgramsNearbyRoute
  '/spaces': typeof SpacesRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/meetup': typeof MeetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/events'
    | '/missions'
    | '/profile'
    | '/programs'
    | '/programs/nearby'
    | '/spaces'
    | '/spaces/$spaceId'
    | '/meetup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/events'
    | '/missions'
    | '/profile'
    | '/programs'
    | '/programs/nearby'
    | '/spaces'
    | '/spaces/$spaceId'
    | '/meetup'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/events'
    | '/missions'
    | '/profile'
    | '/programs'
    | '/programs/nearby'
    | '/spaces'
    | '/spaces/$spaceId'
    | '/meetup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  ProgramsRoute: typeof ProgramsRoute
  SpacesRoute: typeof SpacesRoute
  MeetupRoute: typeof MeetupRoute
}
export interface ProgramsRouteChildren {
  ProgramsNearbyRoute: typeof ProgramsNearbyRoute
}
export interface SpacesRouteChildren {
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/community': { id: '/community'; path: '/community'; fullPath: '/community'; preLoaderRoute: typeof CommunityRouteImport; parentRoute: typeof rootRouteImport }
    '/events': { id: '/events'; path: '/events'; fullPath: '/events'; preLoaderRoute: typeof EventsRouteImport; parentRoute: typeof rootRouteImport }
    '/missions': { id: '/missions'; path: '/missions'; fullPath: '/missions'; preLoaderRoute: typeof MissionsRouteImport; parentRoute: typeof rootRouteImport }
    '/profile': { id: '/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof ProfileRouteImport; parentRoute: typeof rootRouteImport }
    '/programs': { id: '/programs'; path: '/programs'; fullPath: '/programs'; preLoaderRoute: typeof ProgramsRouteImport; parentRoute: typeof rootRouteImport }
    '/programs/nearby': { id: '/programs/nearby'; path: '/nearby'; fullPath: '/programs/nearby'; preLoaderRoute: typeof ProgramsNearbyRouteImport; parentRoute: typeof ProgramsRouteImport }
    '/spaces': { id: '/spaces'; path: '/spaces'; fullPath: '/spaces'; preLoaderRoute: typeof SpacesRouteImport; parentRoute: typeof rootRouteImport }
    '/spaces/$spaceId': { id: '/spaces/$spaceId'; path: '/$spaceId'; fullPath: '/spaces/$spaceId'; preLoaderRoute: typeof SpacesSpaceIdRouteImport; parentRoute: typeof SpacesRouteImport }
    '/meetup': { id: '/meetup'; path: '/meetup'; fullPath: '/meetup'; preLoaderRoute: typeof MeetupRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const programsRouteChildren: ProgramsRouteChildren = { ProgramsNearbyRoute }
const spacesRouteChildren: SpacesRouteChildren = { SpacesSpaceIdRoute }
const rootRouteChildren: RootRouteChildren = { IndexRoute, CommunityRoute, EventsRoute, MissionsRoute, ProfileRoute, ProgramsRoute, SpacesRoute, MeetupRoute }

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

// Attach nested file routes after their parent definitions.
ProgramsRoute._addFileChildren(programsRouteChildren)
SpacesRoute._addFileChildren(spacesRouteChildren)

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
